### PR TITLE
Add email confirmed field (#4)

### PR DESCRIPTION
**Pull request by RoiEXLab**
This adresses #4

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Small suggestion btw...
Instead of returning int values for fields like "banned" etc. You should return bool values. 
Since this would break some code, I'd recommend increasing a major version number

**Comment by RoiEXLab** [comment]
Nevermind, moving this to another issue...

Please npm publish this change...

**Comment by NicolasSiver** [comment]
I think, to reduce the discrepancy between plugin and core, it should inherit object types.
So it should not be a Boolean for the new field. ;)

**Comment by RoiEXLab** [comment]
But the original nodebb api is also providing boolean values...
Internally the objects are retrieved from the db and then set to their respective boolean values before being served as json.
`user.banned = parseInt(user.banned) == 1`

**Comment by NicolasSiver** [comment]
Hm.
I think my main point, that I would prefer to don't grow plugin code, with a hypothesis that plugin will be less affected for breaking changes from the Core team.

**Comment by RoiEXLab** [comment]
I get what you mean, I still think booleans are the way to go...
If you wanted to be really independent,  you could rely on [a single function](https://github.com/NodeBB/NodeBB/blob/b5f8fc815e4eee6166fb3db929b067206a2a7a3f/src/user.js#L93) which I believe returns an object with all the available user data...

**Pull request merged**
